<?php
/**
 * Related Products Tab Template - Default Magento Design
 */
use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;
/** @var $block \Magento\Catalog\Block\Product\ProductList\Related */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$type = $block->getType();
$exist = $block->getItems()->getSize();
$class = $type;
$image = 'related_products_list';
$title = __('Related Products');
$items = $block->getItems();
$limit = 0;
$shuffle = 0;
$isWeightedRandom = 0;
$canItemsAddToCart = $block->canItemsAddToCart();
$showAddTo = true;
$showCart = false;
$templateType = null;
$description = false;
$_item = null;
?>
<?php if ($exist):?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */ $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>">
    <div class="block-title title">
    </div>
    <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart):?>
            <div class="block-actions">
                <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
                <button type="button" class="action select"
                        data-role="select-all"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
            </div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
            <ol class="products list items product-items">
                <?php foreach ($items as $_item):?>
                    <?php $available = ''; ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'):?>
                        <?php if (!$_item->getRequiredOptions()):?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <li class="item product product-item"
                        id="product-item_<?= /* @noEscape */ $_item->getId() ?>"
                        data-shuffle-group="<?= $block->escapeHtmlAttr($_item->getPriority()) ?>" >
                        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                            'display:none;',
                            'li#product-item_' . $_item->getId()
                        ) ?>
                        <div class="product-item-info <?= /* @noEscape */ $available ?>">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product photo product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a
                                            class="product-item-link"
                                            title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?></a>
                                </strong>
                                <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                <?php if ($templateType):?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
                                    && $type == 'related'):?>
                                    <?php if (!$_item->getRequiredOptions()):?>
                                        <div class="field choice related">
                                            <input
                                                type="checkbox"
                                                class="checkbox related"
                                                id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                                name="related_products[]"
                                                value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                            <label class="label"
                                                   for="related-checkbox<?= $block->escapeHtmlAttr($_item->getId())
                                                    ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </label>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <div class="secondary-addto-links actions-secondary"
                                     data-role="add-to-links">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?> 